package Collection;



import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author apple
 */
public class CollectionSwitchBoard extends javax.swing.JFrame {
    
    
    String reportDate;
    Connection con;
    PreparedStatement pst;
    CollectionDAO col;
    ResultSet rs;
    
    String zone;
    double organicWaste;
    double paper;
    double wood;
    double otherBD;
    double plastic;
    double polythene;
    double metal;
    double eWaste;
    double otherNBD;
    
    double grandSum = 0.0;
    double sumBioD = 0.0;
    double sumNBD = 0.0;
    

    /**
     * Creates new form CollectionSwitchBoard
     */
    public CollectionSwitchBoard() {
       
        initComponents();
        col = new CollectionDAO();
        FormLoad();
        txtTotWaste.setEditable(false);
        txtBio.setEditable(false);
        txtNonbio.setEditable(false);
        txtDate.setEditable(false);
    }
    
    private void FormLoad(){ 
        //set current time
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        txtDate.setText(dateFormat.format(date));
        
        //load combo boxes
        rs = col.ZoneValues();
        try {
            while(rs.next()){
               cmbZones.addItem(rs.getString("name"));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(CollectionSwitchBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void formClear(){
        txtOrganic.setText(null);
        txtPaper.setText(null);
        txtWood.setText(null);
        txtOther_bio.setText("");
        txtPlastic.setText("");
        txtPolythene.setText("");
        txtMetal.setText("");
        txtEwaste.setText("");
        txtOthernon_bio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblZone = new javax.swing.JLabel();
        cmbZones = new javax.swing.JComboBox<>();
        lblIncharge = new javax.swing.JLabel();
        txtIncharge = new javax.swing.JTextField();
        lblPolythene = new javax.swing.JLabel();
        txtPolythene = new javax.swing.JTextField();
        lblMetal = new javax.swing.JLabel();
        txtMetal = new javax.swing.JTextField();
        lblEwaste = new javax.swing.JLabel();
        txtEwaste = new javax.swing.JTextField();
        lblOthernon_bio = new javax.swing.JLabel();
        txtOthernon_bio = new javax.swing.JTextField();
        lblPlastic = new javax.swing.JLabel();
        txtPlastic = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOrganic = new javax.swing.JLabel();
        txtOrganic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblPaper = new javax.swing.JLabel();
        txtPaper = new javax.swing.JTextField();
        lblWood = new javax.swing.JLabel();
        txtWood = new javax.swing.JTextField();
        lblOther_bio = new javax.swing.JLabel();
        txtOther_bio = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        txtBio = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblTotWaste = new javax.swing.JLabel();
        txtTotWaste = new javax.swing.JTextField();
        lblBio = new javax.swing.JLabel();
        txtNonbio = new javax.swing.JTextField();
        lblNonbio = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Daily Collection Details Form");

        lblZone.setText("Zone");

        cmbZones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbZonesItemStateChanged(evt);
            }
        });

        lblIncharge.setText("Incharge Officer");

        lblPolythene.setText("Polythene Waste");

        lblMetal.setText("Matel Waste");

        lblEwaste.setText("E Waste");

        lblOthernon_bio.setText("Other Non-Biodegradables");

        lblPlastic.setText("Plastic Waste");

        jLabel14.setText("Weight (Kg)");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("Non-Biodegradable");

        jLabel2.setText("Waste Type :");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Biodegradable");

        lblOrganic.setText("Organic Waste");

        jLabel8.setText("Weight (Kg)");

        lblPaper.setText("Paper Waste");

        lblWood.setText("Wood Waste");

        lblOther_bio.setText("Other Biodegradables");

        btnExit.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBioActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTotWaste.setText("Total Waste Collection");

        lblBio.setText("Biodegradable");

        lblNonbio.setText("Non-Biodegradable");

        jLabel23.setText("(Kg)");

        jLabel24.setText("(Kg)");

        jLabel25.setText("(Kg)");

        btnPrint.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        btnPrint.setText("Print");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel20.setText("Summary of the Day");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblOrganic)
                            .addComponent(lblPaper)
                            .addComponent(lblWood)
                            .addComponent(lblOther_bio))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrganic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPaper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOther_bio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPolythene)
                                    .addComponent(lblMetal)
                                    .addComponent(lblEwaste)
                                    .addComponent(lblOthernon_bio)
                                    .addComponent(lblPlastic)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel12)))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPolythene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMetal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEwaste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOthernon_bio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlastic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblNonbio)
                        .addGap(18, 18, 18)
                        .addComponent(txtNonbio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(lblTotWaste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotWaste)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addGap(268, 268, 268)
                                .addComponent(jLabel25))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblZone)
                                        .addGap(101, 101, 101)
                                        .addComponent(cmbZones, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)
                                        .addComponent(lblIncharge)
                                        .addGap(79, 79, 79)
                                        .addComponent(txtIncharge, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblZone))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbZones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIncharge))
                    .addComponent(txtIncharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel8))
                    .addComponent(jLabel14))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrganic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblPlastic))
                            .addComponent(txtPlastic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblOrganic)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPaper))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblPolythene))
                    .addComponent(txtPolythene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblWood))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblMetal))
                    .addComponent(txtMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOther_bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblEwaste))
                    .addComponent(txtEwaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOther_bio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblOthernon_bio))
                    .addComponent(txtOthernon_bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBio)
                    .addComponent(jLabel24)
                    .addComponent(lblNonbio)
                    .addComponent(txtNonbio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(lblTotWaste)
                    .addComponent(txtTotWaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String msg;
        msg = col.insertCollection(zone);
        
        organicWaste = Double.parseDouble(txtOrganic.getText()); //B1
        paper = Double.parseDouble(txtPaper.getText()); //B2
        wood = Double.parseDouble(txtWood.getText()); //B3
        otherBD = Double.parseDouble(txtOther_bio.getText()); //B4
        plastic = Double.parseDouble (txtPlastic.getText()); //N1
        polythene = Double.parseDouble (txtPolythene.getText()); //N2
        metal = Double.parseDouble(txtMetal.getText()); //N3
        eWaste = Double.parseDouble (txtEwaste.getText()); //N4
        otherNBD = Double.parseDouble(txtOthernon_bio.getText()); //N5
        
        sumBioD += (organicWaste + paper + wood + otherBD);
        sumNBD += (plastic + polythene + metal+ eWaste + otherNBD);
        grandSum += (sumBioD + sumNBD);
        
        col.insertCollectionDetails("B1",organicWaste);
        col.insertCollectionDetails("B2",paper);
        col.insertCollectionDetails("B4",wood);
        col.insertCollectionDetails("B1",otherBD);
        col.insertCollectionDetails("N1",plastic);
        col.insertCollectionDetails("N2",polythene);
        col.insertCollectionDetails("N3",metal);
        col.insertCollectionDetails("N4",eWaste);
        col.insertCollectionDetails("N5",otherNBD);
        
         msg = col.UpdateTypeAmount(sumBioD, sumNBD);
         
        JOptionPane.showMessageDialog(null, msg);
        formClear();
        txtBio.setText(String.valueOf(sumBioD));
        txtNonbio.setText(String.valueOf(sumNBD));
        txtTotWaste.setText(String.valueOf(grandSum));
        
        
        
        //String msg = col.insertCollection(sumBioD, zone, zone)
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBioActionPerformed

    private void cmbZonesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbZonesItemStateChanged
        // TODO add your handling code here:
        txtIncharge.setText(col.getZoneIncharge((String) cmbZones.getSelectedItem()));
        zone = col.getZoneID((String)(cmbZones.getSelectedItem())); 
    }//GEN-LAST:event_cmbZonesItemStateChanged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new Login.Login().setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollectionSwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollectionSwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollectionSwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollectionSwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollectionSwitchBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbZones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBio;
    private javax.swing.JLabel lblEwaste;
    private javax.swing.JLabel lblIncharge;
    private javax.swing.JLabel lblMetal;
    private javax.swing.JLabel lblNonbio;
    private javax.swing.JLabel lblOrganic;
    private javax.swing.JLabel lblOther_bio;
    private javax.swing.JLabel lblOthernon_bio;
    private javax.swing.JLabel lblPaper;
    private javax.swing.JLabel lblPlastic;
    private javax.swing.JLabel lblPolythene;
    private javax.swing.JLabel lblTotWaste;
    private javax.swing.JLabel lblWood;
    private javax.swing.JLabel lblZone;
    private javax.swing.JTextField txtBio;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEwaste;
    private javax.swing.JTextField txtIncharge;
    private javax.swing.JTextField txtMetal;
    private javax.swing.JTextField txtNonbio;
    private javax.swing.JTextField txtOrganic;
    private javax.swing.JTextField txtOther_bio;
    private javax.swing.JTextField txtOthernon_bio;
    private javax.swing.JTextField txtPaper;
    private javax.swing.JTextField txtPlastic;
    private javax.swing.JTextField txtPolythene;
    private javax.swing.JTextField txtTotWaste;
    private javax.swing.JTextField txtWood;
    // End of variables declaration//GEN-END:variables
}
