/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import db.ConnectionProvider;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author apple
 */

public class Zone extends javax.swing.JFrame {

    /**
     * Creates new form Zone
     */
    public Zone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Zone = new javax.swing.JLabel();
        lblZoName = new javax.swing.JLabel();
        lblZoID = new javax.swing.JLabel();
        lblZoLoc = new javax.swing.JLabel();
        lblZoInc = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtZoID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtZoLoc = new javax.swing.JTextField();
        cmbIncharge = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Zone.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Zone.setText("Zone Details");
        getContentPane().add(Zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 394, -1));

        lblZoName.setText("Name");
        getContentPane().add(lblZoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 126, -1, -1));

        lblZoID.setText("Zone ID");
        getContentPane().add(lblZoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 82, -1, -1));

        lblZoLoc.setText("Location");
        getContentPane().add(lblZoLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 175, -1, -1));

        lblZoInc.setText("Incharge");
        getContentPane().add(lblZoInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 218, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 276, -1, -1));

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 276, -1, -1));

        btnEdit.setText("Edit");
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 276, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 276, -1, -1));

        txtZoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZoIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtZoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 82, 186, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 126, 186, -1));
        getContentPane().add(txtZoLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 170, 186, -1));

        cmbIncharge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kaldeen", "Ameer", "Nizam" }));
        getContentPane().add(cmbIncharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 214, 186, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtZoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZoIDActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String zoneID = txtZoID.getText();
        String name = txtName.getText();
        String location = txtZoLoc.getText();
        String incharge = (String)cmbIncharge.getSelectedItem();
        
        String insert = "Insert into ZONE values(?,?,?,?,?)";
        
        PreparedStatement pst;
        Connection con = ConnectionProvider.getCon();
        try {
            pst = con.prepareStatement(insert);
            pst.setString(1, zoneID);
            pst.setString(2, name);
            pst.setString(3, location);
            pst.setString(4, incharge);
            pst.setInt(5, 0);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Added");
            con.close();
            
            txtZoID.setText("");
            txtName.setText("");
            txtZoLoc.setText("");
            txtZoID.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Zone.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Zone;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbIncharge;
    private javax.swing.JLabel lblZoID;
    private javax.swing.JLabel lblZoInc;
    private javax.swing.JLabel lblZoLoc;
    private javax.swing.JLabel lblZoName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtZoID;
    private javax.swing.JTextField txtZoLoc;
    // End of variables declaration//GEN-END:variables
}
