package Type;


import db.ConnectionProvider;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author apple
 */
public class Type extends javax.swing.JFrame {

    /**
     * Creates new form Type
     */
    public Type() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTyAmo = new javax.swing.JLabel();
        txtTyTotCol = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblTyID = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblTyName = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTyName = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Type"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTyAmo.setText("Amount Collected");
        getContentPane().add(lblTyAmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, -1, 32));

        txtTyTotCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTyTotColActionPerformed(evt);
            }
        });
        getContentPane().add(txtTyTotCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 154, 181, 32));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 213, -1, -1));

        lblTyID.setText("ID");
        getContentPane().add(lblTyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 79, 32));

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 213, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 213, -1, -1));

        lblTyName.setText("Name");
        getContentPane().add(lblTyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 79, 26));

        Type.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type.setText("Type");
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 566, 29));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 72, 181, 32));

        txtTyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTyNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtTyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 116, 181, 32));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 213, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTyTotColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTyTotColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTyTotColActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                                       
        // TODO add your handling code here:
        int Amount;
        
        String TypeID = txtID.getText();
        String Name = txtTyName.getText();
        Amount =Integer.parseInt(txtTyTotCol.getText());
        
        String insert = "Insert into Type values(?,?,?)";
        
        PreparedStatement pst;
        Connection con = ConnectionProvider.getCon();
        try {
            pst = con.prepareStatement(insert);
            pst.setString(1, TypeID);
            pst.setString(2, Name);
            pst.setInt(3, Amount);

            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Added");
            con.close();
            
            txtID.setText("");
            txtTyName.setText("");
            txtTyTotCol.setText("");
            txtID.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(Type.class.getName()).log(Level.SEVERE, null, ex);
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtTyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTyNameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Type;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblTyAmo;
    private javax.swing.JLabel lblTyID;
    private javax.swing.JLabel lblTyName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTyName;
    private javax.swing.JTextField txtTyTotCol;
    // End of variables declaration//GEN-END:variables
}
